version: 2
jobs:
  build:
    macos:
      xcode: "11.3.1"
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:a6:1a:8f:d6:4d:9a:6a:9c:42:ff:86:28:87:9e:a9"
      - checkout
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.7.0" > ~/.ruby-version

      - run:
          name: Install Dependencies
          command: bundle install

      - run:
          name: Run Danger
          command: bundle exec danger
          when: always
