version: 2
jobs:
  build:
    macos:
      xcode: "11.3.1"
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
        fingerprints:
          - "ce:14:7b:f9:4b:ac:dd:89:ad:1a:db:2e:08:43:4a:41"
      - checkout
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.7.0" > ~/.ruby-version

      - run:
          name: Install Dependencies
          command: bundle install

      - run:
          name: Run Danger
          command: bundle exec danger
          when: always
