version: 2
jobs:
  build:
    macos:
      xcode: "11.3.1"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.7.0" > ~/.ruby-version

      - run:
          name: Install Dependencies
          command: bundle install

      - run:
          name: Run Danger
          command: bundle exec danger
          when: always
